apiVersion: v1
kind: Secret
metadata:
  name: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: RoboShop@1
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dp
  namespace: roboshop
  labels:
    project: roboshop
    component: mysql
    tier: db
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: mysql
      tier: db
      environment: development
  template:
    metadata:
      labels:
        project: roboshop
        component: mysql
        tier: db
        environment: development
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: mysql
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: mysql
    tier: db
    environment: development
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306   #container port