apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: roboshop
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: RoboShop@1

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
data:
  my.cnf |
    [mysqld]
    innodb_redo_log_capacity = 2G

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dp
  namespace: roboshop
  labels:
    project: roboshop
    component: mysql
    tier: db
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: mysql
      tier: db
      environment: development
  template:
    metadata:
      labels:
        project: roboshop
        component: mysql
        tier: db
        environment: development
    spec:
      containers:
      - name: mysql
        image: 9959087127/mysql1:v1
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: mysql
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 20
          periodSeconds: 5
        volumeMounts:
        - name: mysql-config
          mountpath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
    volumes:
    - name: mysql-config
      configMap:
        name: mysql
---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: mysql
    tier: db
    environment: development
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306   #container port